-- public.call_history definition

-- Drop table

-- DROP TABLE public.call_history;

CREATE TABLE public.call_history (
	call_id int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
	codigo_retorno int4 NULL,
	parametro_id_externo numeric(38, 2) NULL,
	fecha timestamp(6) NULL,
	endpoint varchar(255) NULL,
	respuesta_externa varchar(255) NULL,
	CONSTRAINT call_history_pkey PRIMARY KEY (call_id)
);